# -*- coding: utf-8 -*-
"""meanMedian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y5p_Df2z3o0WVEggrMdnVLPTQX8Tp5k_
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

!wget -O data.csv "https://raw.githubusercontent.com/MainakRepositor/Datasets/master/Salary_Data.csv"

import csv
csv_file = 'data.csv'
data = []
with open(csv_file, 'r', encoding='utf-8') as file:
  csv_reader = csv.reader(file)
  next(csv_reader) #skip header row
  for row in csv_reader:
    data.append(row)

#CONVERT DATA to a NUMPY array
data = np.array(data)

# data_arr = np.array(data, dtype=float)

# data_arr[:,0] = np.round(data_arr[:,0]).astype(int)

data

# naming the dataset
yearsExperience = data[:,0].astype(float)
#salary is stored as str, so converted to float type
salary = data[:,1].astype(float)

# calculate the overall mean and median price
mean_years = np.mean(yearsExperience)
mean_salary = np.mean(salary)
median_years = np.median(yearsExperience)
median_salary = np.median(salary)

print("Mean expYears:", mean_years)
print("Mean salary:", mean_salary)
print("Median expYears:", median_years)
print("Median salary:", median_salary)

plt.figure(figsize=(10,6))
plt.bar(['Mean expYears', 'Median expYears', 'Mean salary', 'Median salary'], [mean_years, median_years, mean_salary, median_salary], color=['skyblue', 'orange', 'black', 'purple'])
plt.title('Overall Mean and Median ExpYears and Salary')
plt.show();

plt.figure(figsize=(24,12))
plt.boxplot(yearsExperience)
plt.title('Boxplot of Exp. years')
plt.ylabel('Years')
plt.plot()

salary_range = np.ptp(salary)
salary_variance = np.var(salary)
salary_std_deviation = np.std(salary)
salary_percentiles = np.percentile(salary, [25, 50, 75])

print("Salary Range:", salary_range)
print("Salary variance:", salary_variance)
print("Salary Standard Deviation:", salary_std_deviation)
print("25th, 50th and 75th Percentiles of Price:", salary_percentiles)

plt.figure(figsize=(15,6))
plt.hist(salary[salary>55000], bins = 20, color = 'skyblue', edgecolor='black')
plt.axvline(salary_percentiles[0], color='red', linestyle='--', label='25th Percentile')
plt.axvline(salary_percentiles[1], color='green', linestyle='--', label='50th Percentile')
plt.axvline(salary_percentiles[2], color='blue', linestyle='--', label='75th Percentile')
plt.xlabel('salary')
# plt.ylabel('will update') # need to add y-label
plt.legend()
plt.plot()