# -*- coding: utf-8 -*-
"""meanMedian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y5p_Df2z3o0WVEggrMdnVLPTQX8Tp5k_
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

!wget -O data.csv "https://raw.githubusercontent.com/MainakRepositor/Datasets/master/Salary_Data.csv"

import csv
csv_file = 'data.csv'
data = []
with open(csv_file, 'r', encoding='utf-8') as file:
  csv_reader = csv.reader(file)
  next(csv_reader) #skip header row
  for row in csv_reader:
    data.append(row)

#CONVERT DATA to a NUMPY array
data = np.array(data)

# data_arr = np.array(data, dtype=float)

# data_arr[:,0] = np.round(data_arr[:,0]).astype(int)

data

# naming the dataset
yearsExperience = data[:,0].astype(float)
#salary is stored as str, so converted to float type
salary = data[:,1].astype(float)

# calculate the overall mean and median price
mean_years = np.mean(yearsExperience)
mean_salary = np.mean(salary)
median_years = np.median(yearsExperience)
median_salary = np.median(salary)

print("Mean expYears:", mean_years)
print("Mean salary:", mean_salary)
print("Median expYears:", median_years)
print("Median salary:", median_salary)

plt.figure(figsize=(10,6))
plt.bar(['Mean expYears', 'Median expYears', 'Mean salary', 'Median salary'], [mean_years, median_years, mean_salary, median_salary], color=['skyblue', 'orange', 'black', 'purple'])
plt.title('Overall Mean and Median ExpYears and Salary')
plt.show();